"""add words table

Revision ID: 09fb83272930
Revises: 
Create Date: 2024-02-09 13:18:51.196672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fb83272930'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('clue', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=True),
    sa.CheckConstraint('LENGTH(word) = length', name=op.f('ck_words_check_word_len')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
