"""add words and clues

Revision ID: 2c181d66922b
Revises: 
Create Date: 2024-02-15 13:35:45.782004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c181d66922b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.CheckConstraint('LENGTH(word) = length', name=op.f('ck_words_check_word_len')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words'))
    )
    op.create_table('clues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_clues_word_id_words')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clues'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clues')
    op.drop_table('words')
    # ### end Alembic commands ###
